modLoader="javafml"
loaderVersion="[53,)"
issueTrackerURL="https://github.com/MattCzyr/Notes/issues"
license="CC BY-NC-SA 4.0"
[[mods]]
    modId="notes"
    version="1.21.3-1.3.1-forge"
    displayName="Notes"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/notes"
    authors="ChaosTheDude"
    description='''
    Clientside in-game notepad.
    '''

[[dependencies.notes]]
    modId="forge"
    mandatory=true
    versionRange="[53,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.3]"
    ordering="NONE"
    side="BOTH"
